In [1]:
print("Hello World")

Hello World


In [2]:
!nvidia-smi

Tue Aug 27 06:39:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
print(torch.__version__)

2.4.0+cu121


In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

**Vector**

In [7]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

**MATRIX**

In [10]:
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix[0]

tensor([7, 8])

In [13]:
matrix[1]

tensor([ 9, 10])

In [14]:
matrix.shape

torch.Size([2, 2])

In [15]:
#Tensor

In [16]:
TENSOR = torch.tensor([[[1, 2 ,3],
                        [3, 6, 9],
                        [2, 4, 5]]])

In [17]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.argmax()


tensor(5)

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

RADOM **TENSORS**

In [22]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4238, 0.1750, 0.8162, 0.8458],
        [0.4268, 0.2699, 0.4179, 0.1140],
        [0.9297, 0.1387, 0.4589, 0.0373]])

In [23]:
random_tensor.ndim

2

In [24]:
random_tensor.shape

torch.Size([3, 4])

In [25]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1045, 0.5860, 0.8093, 0.5887],
        [0.6787, 0.5984, 0.9336, 0.6196],
        [0.1259, 0.6434, 0.2804, 0.7488]])

IMAGE **TENSOR**


In [26]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #((3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [27]:
torch.rand(3, 3)

tensor([[0.4564, 0.6087, 0.3610],
        [0.0202, 0.1593, 0.3604],
        [0.1066, 0.5136, 0.6213]])

In [28]:
zero = torch.zeros(size=(3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
# Ones

ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

In [32]:
random_tensor.dtype

torch.float32

In [33]:
#Create Range

In [34]:
torch.range(0, 10)

<ipython-input-34-cf0dcdb325c8>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [35]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
one_to_ten = torch.arange(start = 1, end = 1000, step = 77)
one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [37]:
#Tensor Like

one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [38]:
ten_zeroes = torch.zeros_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
#Tensor DataTypes

In [40]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])

In [41]:
float_32_tensor.dtype

torch.float32

In [42]:
float_16_tensor = float_32_tensor.to(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [43]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [44]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [45]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [46]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9665, 0.2728, 0.1187, 0.2547],
        [0.2929, 0.7406, 0.0067, 0.0735],
        [0.4901, 0.2677, 0.3563, 0.0133]])

In [47]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9665, 0.2728, 0.1187, 0.2547],
        [0.2929, 0.7406, 0.0067, 0.0735],
        [0.4901, 0.2677, 0.3563, 0.0133]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [48]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [49]:
tensor * 10

tensor([10, 20, 30])

In [50]:
tensor - 10

tensor([-9, -8, -7])

In [51]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [52]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [53]:
#Matrix

tensor * tensor

tensor([1, 4, 9])

In [54]:
torch.matmul(tensor, tensor)

tensor(14)

In [55]:
# 1 * 1 + 2 * 2 + 3 * 3

In [56]:
value = 0
for i in range(len(tensor)):
     value += tensor[i] * tensor[i]
     print(value)

tensor(1)
tensor(5)
tensor(14)


In [57]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 1.14 ms, sys: 25 µs, total: 1.17 ms
Wall time: 1.12 ms


tensor(14)

In [58]:
%%time
torch.mul(tensor, tensor)

CPU times: user 38 µs, sys: 6 µs, total: 44 µs
Wall time: 46.7 µs


tensor([1, 4, 9])

In [59]:
torch.matmul(torch.rand(10, 10), torch.rand(10, 10)).shape
torch.matmul(torch.rand(10, 10), torch.rand(10, 10))

tensor([[3.3417, 1.9487, 2.8885, 2.4854, 2.0248, 2.7113, 1.9226, 1.7037, 2.6296,
         3.3031],
        [3.8466, 2.9837, 3.0525, 1.9117, 2.2171, 2.7353, 2.1302, 1.9995, 2.3576,
         2.5759],
        [2.5533, 1.6914, 2.0260, 1.6082, 2.1236, 2.1430, 1.8636, 1.1275, 1.2849,
         2.2179],
        [2.6177, 1.9927, 2.4913, 2.0706, 1.6725, 2.2375, 1.6295, 1.3141, 1.6974,
         2.2430],
        [3.7958, 2.6617, 3.0023, 2.7509, 2.1964, 2.9779, 2.5598, 2.0532, 2.2327,
         3.2074],
        [2.9534, 2.2931, 3.2599, 1.8342, 1.8583, 2.1902, 2.2116, 2.0239, 1.5334,
         2.6339],
        [3.7898, 2.9055, 3.1819, 2.0365, 2.0603, 2.4286, 2.0543, 2.2966, 2.2087,
         2.6959],
        [3.0189, 1.5505, 2.2155, 1.9260, 2.2681, 2.4808, 1.9781, 1.2905, 2.0278,
         2.9358],
        [3.9759, 2.9355, 3.5934, 2.8233, 2.7252, 3.2515, 2.4589, 2.0989, 2.3301,
         3.3205],
        [3.5688, 2.5417, 3.8356, 2.7281, 2.4278, 2.9810, 2.2987, 2.0901, 2.3754,
         3.1887]])

In [60]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# Fix: Transpose tensor_B so that it can be multiplied with tensor_A
result = torch.matmul(tensor_A, tensor_B.T)

print(result)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [61]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [62]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [63]:
tensor_B.shape

torch.Size([3, 2])

In [64]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [65]:
## Tensor Aggreagtion Min, Max

x = torch.arange(0, 100, 10)

#torch.min(x)



In [66]:
torch.max(x)

tensor(90)

In [67]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [68]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [69]:
x.argmin()

tensor(0)

In [70]:
x[0]

tensor(0)

In [71]:
x.argmax()

tensor(9)

In [72]:
x[9]

tensor(90)

In [73]:
#Reshaping, Squeezing & Unsqueezing & Stacking

x = torch.arange(1., 10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [74]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [75]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [76]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [77]:
#Stack Tensors

x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked


tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [78]:
x_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [79]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [80]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [81]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [82]:
x_original[0, 0, 0] = 728218

In [83]:
# Indexing

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [84]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [85]:
x[0][0]

tensor([1, 2, 3])

In [86]:
x[0][0][0]

tensor(1)

In [87]:
x[0][1][1]

tensor(5)

In [88]:
x[0][2][2]

tensor(9)

In [89]:
x[:, 0]

tensor([[1, 2, 3]])

In [90]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [91]:
x[:, 1, 1]

tensor([5])

In [92]:
x[0, 0, :]

tensor([1, 2, 3])

In [93]:
#Numpy & Torch

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [94]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [95]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [96]:
numpy_tensor.dtype

dtype('float32')

In [97]:
# Change The Tensor

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [98]:
#Reproducibility

# random out of random

torch.rand(3, 3)

tensor([[0.4470, 0.2540, 0.5028],
        [0.9664, 0.3828, 0.2048],
        [0.7176, 0.1803, 0.7493]])

In [99]:
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6865, 0.4492, 0.5150, 0.3100],
        [0.3736, 0.3496, 0.8488, 0.2761],
        [0.9971, 0.3318, 0.7571, 0.5278]])
tensor([[0.1380, 0.4987, 0.5503, 0.3955],
        [0.1876, 0.0754, 0.9283, 0.3129],
        [0.3763, 0.6005, 0.9415, 0.8339]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [100]:
2 == 2

True

In [101]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


# **GPU**

In [102]:
!nvidia-smi

Tue Aug 27 06:39:15 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [103]:

torch.cuda.is_available()

True

In [104]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [105]:
torch.cuda.device_count()

1

In [106]:
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [107]:
#Move Tensor to GPU

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [111]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [112]:
torch.rand(7, 7)

tensor([[0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062, 0.9516],
        [0.0753, 0.8860, 0.5832, 0.3376, 0.8090, 0.5779, 0.9040],
        [0.5547, 0.3423, 0.6343, 0.3644, 0.7104, 0.9464, 0.7890],
        [0.2814, 0.7886, 0.5895, 0.7539, 0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440, 0.7071, 0.6581, 0.4913, 0.8913],
        [0.1447, 0.5315, 0.1587, 0.6542, 0.3278, 0.6532, 0.3958],
        [0.9147, 0.2036, 0.2018, 0.2018, 0.9497, 0.6666, 0.9811]])